### PR TITLE
Remove and ignore parameters.yml

### PR DESCRIPTION
**Pull request by yhoiseth**
I used `platformsh/platformsh-example-symfony` as a starting point to create a Symfony project. When I analyzed my project using SensioLabs Insight, it [complained](https://insight.sensiolabs.com/projects/e87d4c84-7e8d-46b2-884d-f42a181dd7b7/analyses/1?status=violations#468825756) that my `parameters.yml` was checked in to version control.

I didn't even consider the possibility that `parameters.yml` would be checked in to version control, especially since Symfony Standard [ignores it](https://github.com/symfony/symfony-standard/blob/master/.gitignore#L1).

Seeing that `parameters.yml` is automatically created on `composer install` and often contains credentials, I would argue that it shouldn't be included in the example Platform.sh Symfony project.

If I made any mistakes in this pull request, I'd be happy to correct them.

### CODE REVIEW

**Comment by Crell** [comment]
Thanks, @yhoiseth.  You're right, there's not much point to including that file.  However, it currently is still somewhat used.  See https://github.com/platformsh/platformsh-example-symfony/blob/2.8/app/config/config.yml#L2

If you run `composer install --no-interactive` (as we do), and that file doesn't exist, it will get regenerated with default values.  That's largely fine, but the default file is set to use the smtp mailer set to localhost rather than the mail function.  We don't support smtp to localhost, only mail().  So that would result in a broken mail configuration.

The solution would be to specify the mailer explicitly in either `parameters_platform.php` or in `app/config.yml`, before the transport gets used (toward the end of the `config.yml` file).  Off hand I'm not sure which would be better from a Symfony perspective.

Can you update this PR to do one or the other?  That would allow us to remove that `parametes.yml` without any ill-effects.

**Comment by yhoiseth** [comment]
@Crell Thanks for your feedback. I wasn't aware of the issue with smtp to localhost.

I've added a line to `parameters_platform.php` as you suggested.

**Comment by Crell** [comment]
Looks good, thanks!

**Comment by Crell** [comment]
We should do the same for the 3.0 branch (which is actually 3.1, but whatever).  Can you replicate this PR there?

**Comment by yhoiseth** [comment]
@Crell As far as I can tell, `parameters.yml` is [already ignored](https://github.com/platformsh/platformsh-example-symfony/blob/3.0/.gitignore#L1) in the `3.0` branch, and [doesn't exist in the repository](https://github.com/platformsh/platformsh-example-symfony/tree/3.0/app/config).

However, the mailer configuration [is missing](https://github.com/platformsh/platformsh-example-symfony/blob/3.0/app/config/parameters_platform.php) from `parameters_platform.php`.

I would think that the current config (without mailer config in `parameters_platform.php`) has been tested and found to work. Is that a reasonable assumption, or do you think it may be broken?

**Comment by Crell** [comment]
Hm.  I've not tried the mailing support for the Symfony 3.x branch, actually.  Let's go ahead and just add that config line to that branch to be sure.

**Comment by yhoiseth** [comment]
@Crell See #24

**Pull request merged**
